---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: centos-6.6
  - name: centos-7.1
  - name: opentable/win-2008r2-standard-amd64-nocm

suites:
  - name: default
    run_list:
      - recipe[filezilla::default]
    attributes:
